apiVersion: apps/v1
kind: Deployment
metadata:
  name: lga-deployment
  namespace: default
  labels:
    app: lga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lga
  template:
    metadata:
      labels:
        app: lga
    spec:
      containers:
        - name: lga
          image: hakktastic/learn-github-actions:0.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: lga-service
  namespace: default
  labels:
    app: lga
spec:
  selector:
    app: lga
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort