apiVersion: apps/v1
kind: Deployment
metadata:
  name: lga-deployment
  namespace: default
  labels:
    app: lga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lga
  template:
    metadata:
      labels:
        app: lga
    spec:
      containers:
        - name: lga
          image: hakktastic/learn-github-actions:0.0.1-0e902b7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
