name: Bump SCM versions
on: [push]
permissions: write-all
jobs:
  build:
    name: Increment version
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: bump version
        run: mvn clean package