name: Bump SCM versions

on: [push]

permissions: write-all

jobs:
  build:
    name: Increment version
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # dummy
      - name: bump version
        #run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
        run: |
          mvn versions:set -DnewVersion=0.0.2-SNAPSHOT
          mvn versions:commit