name: 👊🏻 Bump SCM version

on: [push]

permissions: write-all

jobs:
  build:
    name: Increment version
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # dummy
      - name: bump version
        run: |
          git config --global user.email "hakktastic@gmail.com"
          git config --global user.name "hakktastic"
          mvn --batch-mode build-helper:parse-version versions:set -DnewVersion=@{parsedVersion.majorVersion}.@{parsedVersion.minorVersion}.@{parsedVersion.incrementalVersion}-SNAPSHOT versions:commit
          mvn versions:commit
          mvn release:prepare -DremoteTagging=false -DscmDevelopmentCommitComment="bump version"